/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.domainmodel.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.urdf.domainmodel.DomainmodelPackage;
import org.xtext.urdf.domainmodel.Origin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Origin</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.urdf.domainmodel.impl.OriginImpl#getX <em>X</em>}</li>
 *   <li>{@link org.xtext.urdf.domainmodel.impl.OriginImpl#getY <em>Y</em>}</li>
 *   <li>{@link org.xtext.urdf.domainmodel.impl.OriginImpl#getZ <em>Z</em>}</li>
 *   <li>{@link org.xtext.urdf.domainmodel.impl.OriginImpl#getRoll <em>Roll</em>}</li>
 *   <li>{@link org.xtext.urdf.domainmodel.impl.OriginImpl#getPitch <em>Pitch</em>}</li>
 *   <li>{@link org.xtext.urdf.domainmodel.impl.OriginImpl#getYaw <em>Yaw</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OriginImpl extends MinimalEObjectImpl.Container implements Origin
{
  /**
   * The default value of the '{@link #getX() <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX()
   * @generated
   * @ordered
   */
  protected static final int X_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getX() <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX()
   * @generated
   * @ordered
   */
  protected int x = X_EDEFAULT;

  /**
   * The default value of the '{@link #getY() <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY()
   * @generated
   * @ordered
   */
  protected static final int Y_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getY() <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY()
   * @generated
   * @ordered
   */
  protected int y = Y_EDEFAULT;

  /**
   * The default value of the '{@link #getZ() <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZ()
   * @generated
   * @ordered
   */
  protected static final int Z_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getZ() <em>Z</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZ()
   * @generated
   * @ordered
   */
  protected int z = Z_EDEFAULT;

  /**
   * The default value of the '{@link #getRoll() <em>Roll</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoll()
   * @generated
   * @ordered
   */
  protected static final int ROLL_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getRoll() <em>Roll</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRoll()
   * @generated
   * @ordered
   */
  protected int roll = ROLL_EDEFAULT;

  /**
   * The default value of the '{@link #getPitch() <em>Pitch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPitch()
   * @generated
   * @ordered
   */
  protected static final int PITCH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPitch() <em>Pitch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPitch()
   * @generated
   * @ordered
   */
  protected int pitch = PITCH_EDEFAULT;

  /**
   * The default value of the '{@link #getYaw() <em>Yaw</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYaw()
   * @generated
   * @ordered
   */
  protected static final int YAW_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getYaw() <em>Yaw</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getYaw()
   * @generated
   * @ordered
   */
  protected int yaw = YAW_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OriginImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainmodelPackage.Literals.ORIGIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getX()
  {
    return x;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setX(int newX)
  {
    int oldX = x;
    x = newX;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.ORIGIN__X, oldX, x));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getY()
  {
    return y;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setY(int newY)
  {
    int oldY = y;
    y = newY;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.ORIGIN__Y, oldY, y));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getZ()
  {
    return z;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setZ(int newZ)
  {
    int oldZ = z;
    z = newZ;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.ORIGIN__Z, oldZ, z));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getRoll()
  {
    return roll;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRoll(int newRoll)
  {
    int oldRoll = roll;
    roll = newRoll;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.ORIGIN__ROLL, oldRoll, roll));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getPitch()
  {
    return pitch;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPitch(int newPitch)
  {
    int oldPitch = pitch;
    pitch = newPitch;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.ORIGIN__PITCH, oldPitch, pitch));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getYaw()
  {
    return yaw;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setYaw(int newYaw)
  {
    int oldYaw = yaw;
    yaw = newYaw;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainmodelPackage.ORIGIN__YAW, oldYaw, yaw));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainmodelPackage.ORIGIN__X:
        return getX();
      case DomainmodelPackage.ORIGIN__Y:
        return getY();
      case DomainmodelPackage.ORIGIN__Z:
        return getZ();
      case DomainmodelPackage.ORIGIN__ROLL:
        return getRoll();
      case DomainmodelPackage.ORIGIN__PITCH:
        return getPitch();
      case DomainmodelPackage.ORIGIN__YAW:
        return getYaw();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainmodelPackage.ORIGIN__X:
        setX((Integer)newValue);
        return;
      case DomainmodelPackage.ORIGIN__Y:
        setY((Integer)newValue);
        return;
      case DomainmodelPackage.ORIGIN__Z:
        setZ((Integer)newValue);
        return;
      case DomainmodelPackage.ORIGIN__ROLL:
        setRoll((Integer)newValue);
        return;
      case DomainmodelPackage.ORIGIN__PITCH:
        setPitch((Integer)newValue);
        return;
      case DomainmodelPackage.ORIGIN__YAW:
        setYaw((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.ORIGIN__X:
        setX(X_EDEFAULT);
        return;
      case DomainmodelPackage.ORIGIN__Y:
        setY(Y_EDEFAULT);
        return;
      case DomainmodelPackage.ORIGIN__Z:
        setZ(Z_EDEFAULT);
        return;
      case DomainmodelPackage.ORIGIN__ROLL:
        setRoll(ROLL_EDEFAULT);
        return;
      case DomainmodelPackage.ORIGIN__PITCH:
        setPitch(PITCH_EDEFAULT);
        return;
      case DomainmodelPackage.ORIGIN__YAW:
        setYaw(YAW_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainmodelPackage.ORIGIN__X:
        return x != X_EDEFAULT;
      case DomainmodelPackage.ORIGIN__Y:
        return y != Y_EDEFAULT;
      case DomainmodelPackage.ORIGIN__Z:
        return z != Z_EDEFAULT;
      case DomainmodelPackage.ORIGIN__ROLL:
        return roll != ROLL_EDEFAULT;
      case DomainmodelPackage.ORIGIN__PITCH:
        return pitch != PITCH_EDEFAULT;
      case DomainmodelPackage.ORIGIN__YAW:
        return yaw != YAW_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (x: ");
    result.append(x);
    result.append(", y: ");
    result.append(y);
    result.append(", z: ");
    result.append(z);
    result.append(", Roll: ");
    result.append(roll);
    result.append(", Pitch: ");
    result.append(pitch);
    result.append(", Yaw: ");
    result.append(yaw);
    result.append(')');
    return result.toString();
  }

} //OriginImpl
