/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.domainmodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.urdf.domainmodel.Link#getInertial <em>Inertial</em>}</li>
 *   <li>{@link org.xtext.urdf.domainmodel.Link#getVisuals <em>Visuals</em>}</li>
 *   <li>{@link org.xtext.urdf.domainmodel.Link#getCollision <em>Collision</em>}</li>
 * </ul>
 *
 * @see org.xtext.urdf.domainmodel.DomainmodelPackage#getLink()
 * @model
 * @generated
 */
public interface Link extends EObject
{
  /**
   * Returns the value of the '<em><b>Inertial</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.urdf.domainmodel.Inertial}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inertial</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inertial</em>' containment reference list.
   * @see org.xtext.urdf.domainmodel.DomainmodelPackage#getLink_Inertial()
   * @model containment="true"
   * @generated
   */
  EList<Inertial> getInertial();

  /**
   * Returns the value of the '<em><b>Visuals</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.urdf.domainmodel.Visual}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Visuals</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visuals</em>' containment reference list.
   * @see org.xtext.urdf.domainmodel.DomainmodelPackage#getLink_Visuals()
   * @model containment="true"
   * @generated
   */
  EList<Visual> getVisuals();

  /**
   * Returns the value of the '<em><b>Collision</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.urdf.domainmodel.Collision}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Collision</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Collision</em>' containment reference list.
   * @see org.xtext.urdf.domainmodel.DomainmodelPackage#getLink_Collision()
   * @model containment="true"
   * @generated
   */
  EList<Collision> getCollision();

} // Link
