/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.domainmodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mass</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.urdf.domainmodel.DomainmodelPackage#getMass()
 * @model
 * @generated
 */
public interface Mass extends EObject
{
} // Mass
