/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.domainmodel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sphere</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.urdf.domainmodel.DomainmodelPackage#getSphere()
 * @model
 * @generated
 */
public interface Sphere extends Geometry
{
} // Sphere
