/*
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.tests

import org.eclipse.xtext.junit4.InjectWith
import org.junit.Assert
import org.junit.Test

@InjectWith(DslInjectorProvider)

class DslGeneratorTest{
	
	//Ideas for tests:
	//Create a couple of links and joint and generate the URDF using the generator. Load the URDF file from the filesystem and 
	// validate against URDF schema. All in one JUnit test


	//Class for creating tests related to generator - below is just a sample test	
	
	@Test 
	def void createLink() {
		val rob = TestAdapter.createTestUrdf
		val myLink = rob.links.get(0)
		Assert.assertEquals("URDFLink1Testname", myLink.name)
	}
	
	

}
