/*
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.urdf.myURDF.Axis;
import org.xtext.urdf.myURDF.Box;
import org.xtext.urdf.myURDF.Calibration;
import org.xtext.urdf.myURDF.Collision;
import org.xtext.urdf.myURDF.Color;
import org.xtext.urdf.myURDF.Cylinder;
import org.xtext.urdf.myURDF.Dynamics;
import org.xtext.urdf.myURDF.Inertia;
import org.xtext.urdf.myURDF.Inertial;
import org.xtext.urdf.myURDF.Joint;
import org.xtext.urdf.myURDF.JointDecoRef;
import org.xtext.urdf.myURDF.JointDecorator;
import org.xtext.urdf.myURDF.JointRef;
import org.xtext.urdf.myURDF.Limit;
import org.xtext.urdf.myURDF.Link;
import org.xtext.urdf.myURDF.LinkDecorator;
import org.xtext.urdf.myURDF.LinkRef;
import org.xtext.urdf.myURDF.Mass;
import org.xtext.urdf.myURDF.Mesh;
import org.xtext.urdf.myURDF.MyURDFPackage;
import org.xtext.urdf.myURDF.Origin;
import org.xtext.urdf.myURDF.Robot;
import org.xtext.urdf.myURDF.SafetyController;
import org.xtext.urdf.myURDF.Sphere;
import org.xtext.urdf.myURDF.Texture;
import org.xtext.urdf.myURDF.Topology;
import org.xtext.urdf.myURDF.URDFAttrFloat;
import org.xtext.urdf.myURDF.URDFAttrINT;
import org.xtext.urdf.myURDF.URDFAttrNumeric;
import org.xtext.urdf.myURDF.URDFAttrSTRING;
import org.xtext.urdf.myURDF.URDFAttrSignedNumeric;
import org.xtext.urdf.myURDF.Visual;
import org.xtext.urdf.services.DslGrammarAccess;

@SuppressWarnings("all")
public class DslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyURDFPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyURDFPackage.AXIS:
				sequence_Axis(context, (Axis) semanticObject); 
				return; 
			case MyURDFPackage.BOX:
				sequence_Box(context, (Box) semanticObject); 
				return; 
			case MyURDFPackage.CALIBRATION:
				sequence_Calibration(context, (Calibration) semanticObject); 
				return; 
			case MyURDFPackage.COLLISION:
				sequence_Collision(context, (Collision) semanticObject); 
				return; 
			case MyURDFPackage.COLOR:
				sequence_Color(context, (Color) semanticObject); 
				return; 
			case MyURDFPackage.CYLINDER:
				sequence_Cylinder(context, (Cylinder) semanticObject); 
				return; 
			case MyURDFPackage.DYNAMICS:
				sequence_Dynamics(context, (Dynamics) semanticObject); 
				return; 
			case MyURDFPackage.INERTIA:
				sequence_Inertia(context, (Inertia) semanticObject); 
				return; 
			case MyURDFPackage.INERTIAL:
				sequence_Inertial(context, (Inertial) semanticObject); 
				return; 
			case MyURDFPackage.JOINT:
				sequence_Joint(context, (Joint) semanticObject); 
				return; 
			case MyURDFPackage.JOINT_DECO_REF:
				sequence_JointDecoRef(context, (JointDecoRef) semanticObject); 
				return; 
			case MyURDFPackage.JOINT_DECORATOR:
				sequence_JointDecorator(context, (JointDecorator) semanticObject); 
				return; 
			case MyURDFPackage.JOINT_REF:
				sequence_JointRef(context, (JointRef) semanticObject); 
				return; 
			case MyURDFPackage.LIMIT:
				sequence_Limit(context, (Limit) semanticObject); 
				return; 
			case MyURDFPackage.LINK:
				sequence_Link(context, (Link) semanticObject); 
				return; 
			case MyURDFPackage.LINK_DECORATOR:
				sequence_LinkDecorator(context, (LinkDecorator) semanticObject); 
				return; 
			case MyURDFPackage.LINK_REF:
				sequence_LinkRef(context, (LinkRef) semanticObject); 
				return; 
			case MyURDFPackage.MASS:
				sequence_Mass(context, (Mass) semanticObject); 
				return; 
			case MyURDFPackage.MESH:
				sequence_Mesh(context, (Mesh) semanticObject); 
				return; 
			case MyURDFPackage.ORIGIN:
				sequence_Origin(context, (Origin) semanticObject); 
				return; 
			case MyURDFPackage.ROBOT:
				sequence_Robot(context, (Robot) semanticObject); 
				return; 
			case MyURDFPackage.SAFETY_CONTROLLER:
				sequence_SafetyController(context, (SafetyController) semanticObject); 
				return; 
			case MyURDFPackage.SPHERE:
				sequence_Sphere(context, (Sphere) semanticObject); 
				return; 
			case MyURDFPackage.TEXTURE:
				sequence_Texture(context, (Texture) semanticObject); 
				return; 
			case MyURDFPackage.TOPOLOGY:
				sequence_Topology(context, (Topology) semanticObject); 
				return; 
			case MyURDFPackage.URDF_ATTR_FLOAT:
				sequence_URDFAttrFloat(context, (URDFAttrFloat) semanticObject); 
				return; 
			case MyURDFPackage.URDF_ATTR_INT:
				sequence_URDFAttrINT(context, (URDFAttrINT) semanticObject); 
				return; 
			case MyURDFPackage.URDF_ATTR_NUMERIC:
				sequence_URDFAttrNumeric(context, (URDFAttrNumeric) semanticObject); 
				return; 
			case MyURDFPackage.URDF_ATTR_STRING:
				sequence_URDFAttrSTRING(context, (URDFAttrSTRING) semanticObject); 
				return; 
			case MyURDFPackage.URDF_ATTR_SIGNED_NUMERIC:
				sequence_URDFAttrSignedNumeric(context, (URDFAttrSignedNumeric) semanticObject); 
				return; 
			case MyURDFPackage.VISUAL:
				sequence_Visual(context, (Visual) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Axis returns Axis
	 *
	 * Constraint:
	 *     (name=ID? x=URDFAttrINT y=URDFAttrINT z=URDFAttrINT)
	 */
	protected void sequence_Axis(ISerializationContext context, Axis semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Box
	 *     Box returns Box
	 *
	 * Constraint:
	 *     (name=ID? height=URDFAttrNumeric length=URDFAttrNumeric width=URDFAttrNumeric)
	 */
	protected void sequence_Box(ISerializationContext context, Box semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Calibration returns Calibration
	 *
	 * Constraint:
	 *     (name=ID? rising=URDFAttrSignedNumeric? falling=URDFAttrSignedNumeric?)
	 */
	protected void sequence_Calibration(ISerializationContext context, Calibration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Collision returns Collision
	 *
	 * Constraint:
	 *     (name=ID? geometry+=Geometry* origin=Origin?)
	 */
	protected void sequence_Collision(ISerializationContext context, Collision semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Material returns Color
	 *     Color returns Color
	 *
	 * Constraint:
	 *     (name=ID? red=URDFAttrFloat green=URDFAttrFloat blue=URDFAttrFloat alpha=URDFAttrFloat)
	 */
	protected void sequence_Color(ISerializationContext context, Color semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Cylinder
	 *     Cylinder returns Cylinder
	 *
	 * Constraint:
	 *     (name=ID? radius=URDFAttrNumeric length=URDFAttrNumeric)
	 */
	protected void sequence_Cylinder(ISerializationContext context, Cylinder semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Dynamics returns Dynamics
	 *
	 * Constraint:
	 *     (name=ID? friction=URDFAttrSignedNumeric? damping=URDFAttrSignedNumeric?)
	 */
	protected void sequence_Dynamics(ISerializationContext context, Dynamics semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Inertia returns Inertia
	 *
	 * Constraint:
	 *     (
	 *         name=ID? 
	 *         ixx=URDFAttrSignedNumeric 
	 *         ixy=URDFAttrSignedNumeric 
	 *         ixz=URDFAttrSignedNumeric 
	 *         iyy=URDFAttrSignedNumeric 
	 *         iyz=URDFAttrSignedNumeric 
	 *         izz=URDFAttrSignedNumeric
	 *     )
	 */
	protected void sequence_Inertia(ISerializationContext context, Inertia semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Inertial returns Inertial
	 *
	 * Constraint:
	 *     (name=ID? inertia=Inertia mass=Mass origin=Origin?)
	 */
	protected void sequence_Inertial(ISerializationContext context, Inertial semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     JointDecoRef returns JointDecoRef
	 *
	 * Constraint:
	 *     (ref=[Joint|ID] decorator=JointDecorator)
	 */
	protected void sequence_JointDecoRef(ISerializationContext context, JointDecoRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.JOINT_DECO_REF__REF) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.JOINT_DECO_REF__REF));
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.JOINT_DECO_REF__DECORATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.JOINT_DECO_REF__DECORATOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getJointDecoRefAccess().getRefJointIDTerminalRuleCall_1_0_1(), semanticObject.getRef());
		feeder.accept(grammarAccess.getJointDecoRefAccess().getDecoratorJointDecoratorParserRuleCall_2_0(), semanticObject.getDecorator());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     JointDecorator returns JointDecorator
	 *
	 * Constraint:
	 *     (limit=Limit? axis=Axis? calibration=Calibration? dynamics=Dynamics? safetycontroller=SafetyController?)
	 */
	protected void sequence_JointDecorator(ISerializationContext context, JointDecorator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     JointRef returns JointRef
	 *
	 * Constraint:
	 *     (fix='->' | rev='r->' | pris='p->' | cont='c->')
	 */
	protected void sequence_JointRef(ISerializationContext context, JointRef semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Joint returns Joint
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         ChildOf=[Link|ID] 
	 *         ParentOf=[Link|ID] 
	 *         Type=JointType 
	 *         isReuseOf=[Joint|ID]? 
	 *         decorator=JointDecorator
	 *     )
	 */
	protected void sequence_Joint(ISerializationContext context, Joint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Limit returns Limit
	 *
	 * Constraint:
	 *     (name=ID? effort=URDFAttrSignedNumeric velocity=URDFAttrSignedNumeric lower=URDFAttrSignedNumeric? upper=URDFAttrSignedNumeric?)
	 */
	protected void sequence_Limit(ISerializationContext context, Limit semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     LinkDecorator returns LinkDecorator
	 *
	 * Constraint:
	 *     (inertial+=Inertial* visual+=Visual* collision+=Collision*)
	 */
	protected void sequence_LinkDecorator(ISerializationContext context, LinkDecorator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     LinkRef returns LinkRef
	 *
	 * Constraint:
	 *     (ref=[Link|ID] decorator=LinkDecorator)
	 */
	protected void sequence_LinkRef(ISerializationContext context, LinkRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.LINK_REF__REF) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.LINK_REF__REF));
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.LINK_REF__DECORATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.LINK_REF__DECORATOR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLinkRefAccess().getRefLinkIDTerminalRuleCall_1_0_1(), semanticObject.getRef());
		feeder.accept(grammarAccess.getLinkRefAccess().getDecoratorLinkDecoratorParserRuleCall_2_0(), semanticObject.getDecorator());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Link returns Link
	 *
	 * Constraint:
	 *     (name=ID isReuseOf=[Link|ID]? decorator=LinkDecorator)
	 */
	protected void sequence_Link(ISerializationContext context, Link semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Mass returns Mass
	 *
	 * Constraint:
	 *     (name=ID? massValueInKilograms=URDFAttrNumeric)
	 */
	protected void sequence_Mass(ISerializationContext context, Mass semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Mesh
	 *     Mesh returns Mesh
	 *
	 * Constraint:
	 *     (name=ID? pathToFile=URDFAttrSTRING dimension=Box?)
	 */
	protected void sequence_Mesh(ISerializationContext context, Mesh semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Origin returns Origin
	 *
	 * Constraint:
	 *     (
	 *         name=ID? 
	 *         x=URDFAttrSignedNumeric 
	 *         y=URDFAttrSignedNumeric 
	 *         z=URDFAttrSignedNumeric 
	 *         roll=URDFAttrSignedNumeric? 
	 *         pitch=URDFAttrSignedNumeric? 
	 *         yaw=URDFAttrSignedNumeric?
	 *     )
	 */
	protected void sequence_Origin(ISerializationContext context, Origin semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Robot returns Robot
	 *
	 * Constraint:
	 *     (name=ID (topologies+=Topology | link+=Link | joint+=Joint | linkrefs+=LinkRef)*)
	 */
	protected void sequence_Robot(ISerializationContext context, Robot semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SafetyController returns SafetyController
	 *
	 * Constraint:
	 *     (
	 *         name=ID? 
	 *         softLowerLimit=URDFAttrSignedNumeric? 
	 *         softUpperLimit=URDFAttrSignedNumeric? 
	 *         k_position=URDFAttrSignedNumeric? 
	 *         k_velocity=URDFAttrSignedNumeric
	 *     )
	 */
	protected void sequence_SafetyController(ISerializationContext context, SafetyController semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Geometry returns Sphere
	 *     Sphere returns Sphere
	 *
	 * Constraint:
	 *     (name=ID? radius=URDFAttrNumeric)
	 */
	protected void sequence_Sphere(ISerializationContext context, Sphere semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Material returns Texture
	 *     Texture returns Texture
	 *
	 * Constraint:
	 *     (name=ID? pathToFile=URDFAttrSTRING)
	 */
	protected void sequence_Texture(ISerializationContext context, Texture semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Topology returns Topology
	 *
	 * Constraint:
	 *     (parent=[Link|ID] (joint=JointRef child=Topology)?)
	 */
	protected void sequence_Topology(ISerializationContext context, Topology semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrFloat returns URDFAttrFloat
	 *
	 * Constraint:
	 *     value=FLOAT
	 */
	protected void sequence_URDFAttrFloat(ISerializationContext context, URDFAttrFloat semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.URDF_ATTR_FLOAT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.URDF_ATTR_FLOAT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrFloatAccess().getValueFLOATParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrINT returns URDFAttrINT
	 *
	 * Constraint:
	 *     value=INT
	 */
	protected void sequence_URDFAttrINT(ISerializationContext context, URDFAttrINT semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.URDF_ATTR_INT__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.URDF_ATTR_INT__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrINTAccess().getValueINTTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrNumeric returns URDFAttrNumeric
	 *
	 * Constraint:
	 *     value=NUMERIC
	 */
	protected void sequence_URDFAttrNumeric(ISerializationContext context, URDFAttrNumeric semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.URDF_ATTR_NUMERIC__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.URDF_ATTR_NUMERIC__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrNumericAccess().getValueNUMERICParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrSTRING returns URDFAttrSTRING
	 *
	 * Constraint:
	 *     value=STRING
	 */
	protected void sequence_URDFAttrSTRING(ISerializationContext context, URDFAttrSTRING semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.URDF_ATTR_STRING__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.URDF_ATTR_STRING__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrSTRINGAccess().getValueSTRINGTerminalRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     URDFAttrSignedNumeric returns URDFAttrSignedNumeric
	 *
	 * Constraint:
	 *     value=SIGNED_NUMERIC
	 */
	protected void sequence_URDFAttrSignedNumeric(ISerializationContext context, URDFAttrSignedNumeric semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyURDFPackage.Literals.URDF_ATTR_SIGNED_NUMERIC__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyURDFPackage.Literals.URDF_ATTR_SIGNED_NUMERIC__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getURDFAttrSignedNumericAccess().getValueSIGNED_NUMERICParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Visual returns Visual
	 *
	 * Constraint:
	 *     (name=ID? geometry+=Geometry* origin=Origin?)
	 */
	protected void sequence_Visual(ISerializationContext context, Visual semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
