/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.myURDF;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Joint Decorator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.urdf.myURDF.JointDecorator#getAxis <em>Axis</em>}</li>
 *   <li>{@link org.xtext.urdf.myURDF.JointDecorator#getLimit <em>Limit</em>}</li>
 *   <li>{@link org.xtext.urdf.myURDF.JointDecorator#getCalibration <em>Calibration</em>}</li>
 *   <li>{@link org.xtext.urdf.myURDF.JointDecorator#getDynamics <em>Dynamics</em>}</li>
 *   <li>{@link org.xtext.urdf.myURDF.JointDecorator#getSafetycontroller <em>Safetycontroller</em>}</li>
 * </ul>
 *
 * @see org.xtext.urdf.myURDF.MyURDFPackage#getJointDecorator()
 * @model
 * @generated
 */
public interface JointDecorator extends EObject {
	/**
	 * Returns the value of the '<em><b>Axis</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Axis</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Axis</em>' containment reference.
	 * @see #setAxis(Axis)
	 * @see org.xtext.urdf.myURDF.MyURDFPackage#getJointDecorator_Axis()
	 * @model containment="true"
	 * @generated
	 */
	Axis getAxis();

	/**
	 * Sets the value of the '{@link org.xtext.urdf.myURDF.JointDecorator#getAxis <em>Axis</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Axis</em>' containment reference.
	 * @see #getAxis()
	 * @generated
	 */
	void setAxis(Axis value);

	/**
	 * Returns the value of the '<em><b>Limit</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Limit</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Limit</em>' containment reference.
	 * @see #setLimit(Limit)
	 * @see org.xtext.urdf.myURDF.MyURDFPackage#getJointDecorator_Limit()
	 * @model containment="true"
	 * @generated
	 */
	Limit getLimit();

	/**
	 * Sets the value of the '{@link org.xtext.urdf.myURDF.JointDecorator#getLimit <em>Limit</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Limit</em>' containment reference.
	 * @see #getLimit()
	 * @generated
	 */
	void setLimit(Limit value);

	/**
	 * Returns the value of the '<em><b>Calibration</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Calibration</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Calibration</em>' containment reference.
	 * @see #setCalibration(Calibration)
	 * @see org.xtext.urdf.myURDF.MyURDFPackage#getJointDecorator_Calibration()
	 * @model containment="true"
	 * @generated
	 */
	Calibration getCalibration();

	/**
	 * Sets the value of the '{@link org.xtext.urdf.myURDF.JointDecorator#getCalibration <em>Calibration</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Calibration</em>' containment reference.
	 * @see #getCalibration()
	 * @generated
	 */
	void setCalibration(Calibration value);

	/**
	 * Returns the value of the '<em><b>Dynamics</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Dynamics</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Dynamics</em>' containment reference.
	 * @see #setDynamics(Dynamics)
	 * @see org.xtext.urdf.myURDF.MyURDFPackage#getJointDecorator_Dynamics()
	 * @model containment="true"
	 * @generated
	 */
	Dynamics getDynamics();

	/**
	 * Sets the value of the '{@link org.xtext.urdf.myURDF.JointDecorator#getDynamics <em>Dynamics</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Dynamics</em>' containment reference.
	 * @see #getDynamics()
	 * @generated
	 */
	void setDynamics(Dynamics value);

	/**
	 * Returns the value of the '<em><b>Safetycontroller</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Safetycontroller</em>' containment reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Safetycontroller</em>' containment reference.
	 * @see #setSafetycontroller(SafetyController)
	 * @see org.xtext.urdf.myURDF.MyURDFPackage#getJointDecorator_Safetycontroller()
	 * @model containment="true"
	 * @generated
	 */
	SafetyController getSafetycontroller();

	/**
	 * Sets the value of the '{@link org.xtext.urdf.myURDF.JointDecorator#getSafetycontroller <em>Safetycontroller</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Safetycontroller</em>' containment reference.
	 * @see #getSafetycontroller()
	 * @generated
	 */
	void setSafetycontroller(SafetyController value);

} // JointDecorator
