/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.myURDF;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Re Usable Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.urdf.myURDF.ReUsableRef#getReuseable <em>Reuseable</em>}</li>
 * </ul>
 *
 * @see org.xtext.urdf.myURDF.MyURDFPackage#getReUsableRef()
 * @model
 * @generated
 */
public interface ReUsableRef extends Ref {
	/**
	 * Returns the value of the '<em><b>Reuseable</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <p>
	 * If the meaning of the '<em>Reuseable</em>' reference isn't clear,
	 * there really should be more of a description here...
	 * </p>
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Reuseable</em>' reference.
	 * @see #setReuseable(ReUseAble)
	 * @see org.xtext.urdf.myURDF.MyURDFPackage#getReUsableRef_Reuseable()
	 * @model
	 * @generated
	 */
	ReUseAble getReuseable();

	/**
	 * Sets the value of the '{@link org.xtext.urdf.myURDF.ReUsableRef#getReuseable <em>Reuseable</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Reuseable</em>' reference.
	 * @see #getReuseable()
	 * @generated
	 */
	void setReuseable(ReUseAble value);

} // ReUsableRef
