/*
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.urdf.ide.contentassist.antlr.internal.InternalDslParser;
import org.xtext.urdf.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Inject
	private DslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMaterialAccess().getAlternatives(), "rule__Material__Alternatives");
					put(grammarAccess.getGeometryAccess().getAlternatives(), "rule__Geometry__Alternatives");
					put(grammarAccess.getNLAccess().getAlternatives(), "rule__NL__Alternatives");
					put(grammarAccess.getJointTypeAccess().getAlternatives(), "rule__JointType__Alternatives");
					put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getJointAccess().getGroup(), "rule__Joint__Group__0");
					put(grammarAccess.getInertialAccess().getGroup(), "rule__Inertial__Group__0");
					put(grammarAccess.getVisualAccess().getGroup(), "rule__Visual__Group__0");
					put(grammarAccess.getCollisionAccess().getGroup(), "rule__Collision__Group__0");
					put(grammarAccess.getOriginAccess().getGroup(), "rule__Origin__Group__0");
					put(grammarAccess.getMassAccess().getGroup(), "rule__Mass__Group__0");
					put(grammarAccess.getInertiaAccess().getGroup(), "rule__Inertia__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getTextureAccess().getGroup(), "rule__Texture__Group__0");
					put(grammarAccess.getBoxAccess().getGroup(), "rule__Box__Group__0");
					put(grammarAccess.getCylinderAccess().getGroup(), "rule__Cylinder__Group__0");
					put(grammarAccess.getMeshAccess().getGroup(), "rule__Mesh__Group__0");
					put(grammarAccess.getSphereAccess().getGroup(), "rule__Sphere__Group__0");
					put(grammarAccess.getLimitAccess().getGroup(), "rule__Limit__Group__0");
					put(grammarAccess.getAxisAccess().getGroup(), "rule__Axis__Group__0");
					put(grammarAccess.getAxisAccess().getGroup_2(), "rule__Axis__Group_2__0");
					put(grammarAccess.getAxisAccess().getGroup_3(), "rule__Axis__Group_3__0");
					put(grammarAccess.getAxisAccess().getGroup_4(), "rule__Axis__Group_4__0");
					put(grammarAccess.getCalibrationAccess().getGroup(), "rule__Calibration__Group__0");
					put(grammarAccess.getCalibrationAccess().getGroup_2(), "rule__Calibration__Group_2__0");
					put(grammarAccess.getCalibrationAccess().getGroup_3(), "rule__Calibration__Group_3__0");
					put(grammarAccess.getDynamicsAccess().getGroup(), "rule__Dynamics__Group__0");
					put(grammarAccess.getDynamicsAccess().getGroup_2(), "rule__Dynamics__Group_2__0");
					put(grammarAccess.getDynamicsAccess().getGroup_3(), "rule__Dynamics__Group_3__0");
					put(grammarAccess.getMimicAccess().getGroup(), "rule__Mimic__Group__0");
					put(grammarAccess.getMimicAccess().getGroup_2(), "rule__Mimic__Group_2__0");
					put(grammarAccess.getMimicAccess().getGroup_3(), "rule__Mimic__Group_3__0");
					put(grammarAccess.getSafetyControllerAccess().getGroup(), "rule__SafetyController__Group__0");
					put(grammarAccess.getSafetyControllerAccess().getGroup_2(), "rule__SafetyController__Group_2__0");
					put(grammarAccess.getSafetyControllerAccess().getGroup_3(), "rule__SafetyController__Group_3__0");
					put(grammarAccess.getSafetyControllerAccess().getGroup_4(), "rule__SafetyController__Group_4__0");
					put(grammarAccess.getSafetyControllerAccess().getGroup_5(), "rule__SafetyController__Group_5__0");
					put(grammarAccess.getFLOATAccess().getGroup(), "rule__FLOAT__Group__0");
					put(grammarAccess.getRobotAccess().getNameAssignment_1(), "rule__Robot__NameAssignment_1");
					put(grammarAccess.getRobotAccess().getLinkAssignment_2(), "rule__Robot__LinkAssignment_2");
					put(grammarAccess.getRobotAccess().getJointAssignment_3(), "rule__Robot__JointAssignment_3");
					put(grammarAccess.getLinkAccess().getNameAssignment_2(), "rule__Link__NameAssignment_2");
					put(grammarAccess.getLinkAccess().getInertialAssignment_3(), "rule__Link__InertialAssignment_3");
					put(grammarAccess.getLinkAccess().getVisualsAssignment_4(), "rule__Link__VisualsAssignment_4");
					put(grammarAccess.getLinkAccess().getCollisionAssignment_5(), "rule__Link__CollisionAssignment_5");
					put(grammarAccess.getJointAccess().getNameAssignment_1(), "rule__Joint__NameAssignment_1");
					put(grammarAccess.getJointAccess().getTypeAssignment_2(), "rule__Joint__TypeAssignment_2");
					put(grammarAccess.getJointAccess().getChildOfAssignment_3(), "rule__Joint__ChildOfAssignment_3");
					put(grammarAccess.getJointAccess().getParentOfAssignment_4(), "rule__Joint__ParentOfAssignment_4");
					put(grammarAccess.getJointAccess().getLimitAssignment_5(), "rule__Joint__LimitAssignment_5");
					put(grammarAccess.getJointAccess().getAxisAssignment_6(), "rule__Joint__AxisAssignment_6");
					put(grammarAccess.getJointAccess().getOriginAssignment_7(), "rule__Joint__OriginAssignment_7");
					put(grammarAccess.getJointAccess().getCalibrationAssignment_8(), "rule__Joint__CalibrationAssignment_8");
					put(grammarAccess.getJointAccess().getDynamicsAssignment_9(), "rule__Joint__DynamicsAssignment_9");
					put(grammarAccess.getJointAccess().getMimicAssignment_10(), "rule__Joint__MimicAssignment_10");
					put(grammarAccess.getJointAccess().getSafetycontrollerAssignment_11(), "rule__Joint__SafetycontrollerAssignment_11");
					put(grammarAccess.getInertialAccess().getOriginAssignment_0(), "rule__Inertial__OriginAssignment_0");
					put(grammarAccess.getInertialAccess().getMassAssignment_1(), "rule__Inertial__MassAssignment_1");
					put(grammarAccess.getInertialAccess().getInertiaAssignment_2(), "rule__Inertial__InertiaAssignment_2");
					put(grammarAccess.getVisualAccess().getMaterialAssignment_0(), "rule__Visual__MaterialAssignment_0");
					put(grammarAccess.getVisualAccess().getOriginAssignment_1(), "rule__Visual__OriginAssignment_1");
					put(grammarAccess.getVisualAccess().getGeometryAssignment_2(), "rule__Visual__GeometryAssignment_2");
					put(grammarAccess.getCollisionAccess().getGeometryAssignment_0(), "rule__Collision__GeometryAssignment_0");
					put(grammarAccess.getCollisionAccess().getOriginAssignment_1(), "rule__Collision__OriginAssignment_1");
					put(grammarAccess.getOriginAccess().getXAssignment_2(), "rule__Origin__XAssignment_2");
					put(grammarAccess.getOriginAccess().getYAssignment_3(), "rule__Origin__YAssignment_3");
					put(grammarAccess.getOriginAccess().getZAssignment_4(), "rule__Origin__ZAssignment_4");
					put(grammarAccess.getOriginAccess().getRollAssignment_5(), "rule__Origin__RollAssignment_5");
					put(grammarAccess.getOriginAccess().getPitchAssignment_6(), "rule__Origin__PitchAssignment_6");
					put(grammarAccess.getOriginAccess().getYawAssignment_7(), "rule__Origin__YawAssignment_7");
					put(grammarAccess.getLimitAccess().getLowerAssignment_2(), "rule__Limit__LowerAssignment_2");
					put(grammarAccess.getLimitAccess().getUpperAssignment_3(), "rule__Limit__UpperAssignment_3");
					put(grammarAccess.getLimitAccess().getEffortAssignment_4(), "rule__Limit__EffortAssignment_4");
					put(grammarAccess.getLimitAccess().getVelocityAssignment_5(), "rule__Limit__VelocityAssignment_5");
					put(grammarAccess.getAxisAccess().getXAssignment_2_1(), "rule__Axis__XAssignment_2_1");
					put(grammarAccess.getAxisAccess().getYAssignment_3_1(), "rule__Axis__YAssignment_3_1");
					put(grammarAccess.getAxisAccess().getZAssignment_4_1(), "rule__Axis__ZAssignment_4_1");
					put(grammarAccess.getCalibrationAccess().getRisingAssignment_2_1(), "rule__Calibration__RisingAssignment_2_1");
					put(grammarAccess.getCalibrationAccess().getFallingAssignment_3_1(), "rule__Calibration__FallingAssignment_3_1");
					put(grammarAccess.getDynamicsAccess().getFrictionAssignment_2_1(), "rule__Dynamics__FrictionAssignment_2_1");
					put(grammarAccess.getDynamicsAccess().getDampingAssignment_3_1(), "rule__Dynamics__DampingAssignment_3_1");
					put(grammarAccess.getMimicAccess().getMultiplierAssignment_2_1(), "rule__Mimic__MultiplierAssignment_2_1");
					put(grammarAccess.getMimicAccess().getOffSetAssignment_3_1(), "rule__Mimic__OffSetAssignment_3_1");
					put(grammarAccess.getSafetyControllerAccess().getSoftLowerLimitAssignment_2_1(), "rule__SafetyController__SoftLowerLimitAssignment_2_1");
					put(grammarAccess.getSafetyControllerAccess().getSoftUpperLimitAssignment_3_1(), "rule__SafetyController__SoftUpperLimitAssignment_3_1");
					put(grammarAccess.getSafetyControllerAccess().getK_positionAssignment_4_1(), "rule__SafetyController__K_positionAssignment_4_1");
					put(grammarAccess.getSafetyControllerAccess().getK_velocityAssignment_5_1(), "rule__SafetyController__K_velocityAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalDslParser typedParser = (InternalDslParser) parser;
			typedParser.entryRuleRobot();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
