<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myURDF" nsURI="http://www.itu.dk/uRDF" nsPrefix="myURDF">
  <eClassifiers xsi:type="ecore:EClass" name="Robot" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" upperBound="-1"
        eType="#//Joint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topologies" upperBound="-1"
        eType="#//Topology" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addto" upperBound="-1"
        eType="#//AddTo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReUseAble"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReuseOf" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reuse" upperBound="-1"
        eType="#//Reuse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inertial" eType="#//Inertial"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visual" upperBound="-1"
        eType="#//Visual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collision" upperBound="-1"
        eType="#//Collision" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromTopo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reuse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="add" eType="#//ReUseAble"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edit" eType="#//AssignNewValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ref"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReUsableRef" eSuperTypes="#//Ref">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reuseable" eType="#//ReUseAble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrSignedNumeric" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrFloat" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrINT" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrNumeric" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrSTRING" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DotExpression" eSuperTypes="#//Ref">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Ref" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//ReUseAble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inertial" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inertia" eType="#//Inertia"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mass" eType="#//Mass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visual" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geometry" lowerBound="1"
        eType="#//Geometry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" eType="#//Material"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inertia" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ixx" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ixy" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ixz" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="izz" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iyy" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iyz" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mass" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="massKilogram" lowerBound="1"
        eType="#//URDFAttrSignedNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Origin" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="z" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yaw" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pitch" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roll" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collision" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geometry" lowerBound="1"
        eType="#//Geometry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry" eSuperTypes="#//ReUseAble"/>
  <eClassifiers xsi:type="ecore:EClass" name="Box" eSuperTypes="#//Geometry #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" lowerBound="1" eType="#//URDFAttrNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cylinder" eSuperTypes="#//Geometry #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radius" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mesh" eSuperTypes="#//Geometry #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathToFile" lowerBound="1"
        eType="#//URDFAttrSTRING" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sphere" eSuperTypes="#//Geometry #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radius" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material" eSuperTypes="#//ReUseAble"/>
  <eClassifiers xsi:type="ecore:EClass" name="Texture" eSuperTypes="#//Material #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathToFile" lowerBound="1"
        eType="#//URDFAttrSTRING" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color" eSuperTypes="#//Material #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="red" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="green" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blue" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alpha" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Joint" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReuseOf" eType="#//Joint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childOf" lowerBound="1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentOf" lowerBound="1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//JointType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis" eType="#//Axis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="limit" eType="#//Limit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calibration" eType="#//Calibration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamics" eType="#//Dynamics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reuse" upperBound="-1"
        eType="#//Reuse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safetycontroller" eType="#//SafetyController"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromTopo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JointType">
    <eLiterals name="fixed" literal="fixed"/>
    <eLiterals name="revolute" value="1"/>
    <eLiterals name="prismatic" value="2"/>
    <eLiterals name="continuous" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Axis" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" lowerBound="1" eType="#//URDFAttrINT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" lowerBound="1" eType="#//URDFAttrINT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="z" lowerBound="1" eType="#//URDFAttrINT"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Limit" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effort" lowerBound="1"
        eType="#//URDFAttrSignedNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="velocity" lowerBound="1"
        eType="#//URDFAttrSignedNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calibration" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rising" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falling" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dynamics" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="friction" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="damping" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyController" eSuperTypes="#//ReUseAble #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="k_velocity" lowerBound="1"
        eType="#//URDFAttrSignedNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="k_position" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softLowerLimit" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softUpperLimit" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topology">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" eType="#//JointRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Topology"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JointRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rev" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pris" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cont" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssignNewValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="getRef" lowerBound="1"
        eType="#//Ref" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newReuseable" eType="#//ReUseAble"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddTo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" eType="#//Joint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="add" lowerBound="1" eType="#//ReUseAble"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//ID"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
