<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myURDF" nsURI="http://www.itu.dk/uRDF" nsPrefix="myURDF">
   <eClassifiers xsi:type="ecore:EClass" name="Robot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topologies" upperBound="-1"
        eType="#//Topology" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" upperBound="-1"
        eType="#//Joint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkrefs" upperBound="-1"
        eType="#//LinkRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topology">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="joint" eType="#//JointRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" eType="#//Topology"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReuseOf" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorator" eType="#//LinkDecorator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkDecorator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inertial" upperBound="-1"
        eType="#//Inertial" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visual" upperBound="-1"
        eType="#//Visual" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collision" upperBound="-1"
        eType="#//Collision" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorator" lowerBound="1"
        eType="#//LinkDecorator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Joint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChildOf" lowerBound="1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParentOf" lowerBound="1"
        eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//JointType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReuseOf" eType="#//Joint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorator" eType="#//JointDecorator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JointType">
    <eLiterals name="fixed" literal="Fixed"/>
    <eLiterals name="revolute" value="1" literal="Revolute"/>
    <eLiterals name="prismatic" value="2" literal="Prismatic"/>
    <eLiterals name="continuous" value="3" literal="Continuous"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JointRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rev" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pris" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cont" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inertial">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inertia" lowerBound="1"
        eType="#//Inertia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mass" lowerBound="1" eType="#//Mass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inertia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ixx" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ixy" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ixz" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iyy" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iyz" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="izz" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visual">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geometry" lowerBound="1"
        upperBound="-1" eType="#//Geometry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Geometry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Box" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" lowerBound="1" eType="#//URDFAttrNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cylinder" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radius" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collision">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="wildcards" value=""/>
        <details key="name" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="geometry" upperBound="-1"
        eType="#//Geometry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" eType="#//Origin"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Origin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="z" lowerBound="1" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roll" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pitch" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yaw" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="massValueInKilograms" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrSignedNumeric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrFloat">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrINT">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrNumeric">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URDFAttrSTRING">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mesh" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathToFile" lowerBound="1"
        eType="#//URDFAttrSTRING" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" eType="#//Box"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sphere" eSuperTypes="#//Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="radius" lowerBound="1"
        eType="#//URDFAttrNumeric" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color" eSuperTypes="#//Material">
    <eStructuralFeatures xsi:type="ecore:EReference" name="red" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="green" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blue" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alpha" lowerBound="1" eType="#//URDFAttrFloat"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Texture" eSuperTypes="#//Material">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathToFile" lowerBound="1"
        eType="#//URDFAttrSTRING" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Limit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effort" lowerBound="1"
        eType="#//URDFAttrSignedNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="velocity" lowerBound="1"
        eType="#//URDFAttrSignedNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lower" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Axis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="x" lowerBound="1" eType="#//URDFAttrINT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="y" lowerBound="1" eType="#//URDFAttrINT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="z" lowerBound="1" eType="#//URDFAttrINT"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JointDecorator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="axis" eType="#//Axis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="limit" eType="#//Limit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calibration" eType="#//Calibration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamics" eType="#//Dynamics"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safetycontroller" eType="#//SafetyController"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Calibration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rising" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="falling" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dynamics">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friction" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="damping" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="k_velocity" lowerBound="1"
        eType="#//URDFAttrSignedNumeric" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="k_position" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softUpperLimit" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="softLowerLimit" eType="#//URDFAttrSignedNumeric"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JointDecoRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decorator" lowerBound="1"
        eType="#//JointDecorator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" lowerBound="1" eType="#//Joint"/>
  </eClassifiers>
  </ecore:EPackage>
