/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.myURDF.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.InternalEObject;
import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.urdf.myURDF.Mass;
import org.xtext.urdf.myURDF.MyURDFPackage;
import org.xtext.urdf.myURDF.URDFAttrNumeric;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mass</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.urdf.myURDF.impl.MassImpl#getMassValueInKilograms <em>Mass Value In Kilograms</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MassImpl extends NamedElementImpl implements Mass {
	/**
	 * The cached value of the '{@link #getMassValueInKilograms() <em>Mass Value In Kilograms</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getMassValueInKilograms()
	 * @generated
	 * @ordered
	 */
	protected URDFAttrNumeric massValueInKilograms;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MassImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MyURDFPackage.Literals.MASS;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public URDFAttrNumeric getMassValueInKilograms() {
		return massValueInKilograms;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetMassValueInKilograms(URDFAttrNumeric newMassValueInKilograms, NotificationChain msgs) {
		URDFAttrNumeric oldMassValueInKilograms = massValueInKilograms;
		massValueInKilograms = newMassValueInKilograms;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS, oldMassValueInKilograms, newMassValueInKilograms);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setMassValueInKilograms(URDFAttrNumeric newMassValueInKilograms) {
		if (newMassValueInKilograms != massValueInKilograms) {
			NotificationChain msgs = null;
			if (massValueInKilograms != null)
				msgs = ((InternalEObject)massValueInKilograms).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS, null, msgs);
			if (newMassValueInKilograms != null)
				msgs = ((InternalEObject)newMassValueInKilograms).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS, null, msgs);
			msgs = basicSetMassValueInKilograms(newMassValueInKilograms, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS, newMassValueInKilograms, newMassValueInKilograms));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS:
				return basicSetMassValueInKilograms(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS:
				return getMassValueInKilograms();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS:
				setMassValueInKilograms((URDFAttrNumeric)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS:
				setMassValueInKilograms((URDFAttrNumeric)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case MyURDFPackage.MASS__MASS_VALUE_IN_KILOGRAMS:
				return massValueInKilograms != null;
		}
		return super.eIsSet(featureID);
	}

} //MassImpl
