/**
 * generated by Xtext 2.10.0
 */
package org.xtext.urdf.myURDF.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.urdf.myURDF.MyURDFPackage;
import org.xtext.urdf.myURDF.ReUsableRef;
import org.xtext.urdf.myURDF.ReUseAble;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Re Usable Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.urdf.myURDF.impl.ReUsableRefImpl#getReuseable <em>Reuseable</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReUsableRefImpl extends RefImpl implements ReUsableRef {
	/**
	 * The cached value of the '{@link #getReuseable() <em>Reuseable</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getReuseable()
	 * @generated
	 * @ordered
	 */
	protected ReUseAble reuseable;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReUsableRefImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MyURDFPackage.Literals.RE_USABLE_REF;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ReUseAble getReuseable() {
		if (reuseable != null && reuseable.eIsProxy()) {
			InternalEObject oldReuseable = (InternalEObject)reuseable;
			reuseable = (ReUseAble)eResolveProxy(oldReuseable);
			if (reuseable != oldReuseable) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyURDFPackage.RE_USABLE_REF__REUSEABLE, oldReuseable, reuseable));
			}
		}
		return reuseable;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ReUseAble basicGetReuseable() {
		return reuseable;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setReuseable(ReUseAble newReuseable) {
		ReUseAble oldReuseable = reuseable;
		reuseable = newReuseable;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, MyURDFPackage.RE_USABLE_REF__REUSEABLE, oldReuseable, reuseable));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case MyURDFPackage.RE_USABLE_REF__REUSEABLE:
				if (resolve) return getReuseable();
				return basicGetReuseable();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case MyURDFPackage.RE_USABLE_REF__REUSEABLE:
				setReuseable((ReUseAble)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case MyURDFPackage.RE_USABLE_REF__REUSEABLE:
				setReuseable((ReUseAble)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case MyURDFPackage.RE_USABLE_REF__REUSEABLE:
				return reuseable != null;
		}
		return super.eIsSet(featureID);
	}

} //ReUsableRefImpl
